language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: La5YvK1rHnDYQLB6xkdQgJrR7DzJaBznrg0XV5Q/njxqgGmgpfVO/91WHV+Zi6SmFd3Kt7UejD0C5j/KzH0VGjlmsehi5UtCR9ayRO3gs0B5OZjoMhdmyG+GFq5ceWuhvSWEs2ADavXolWwVM19kra6bw6hFBcD3myOJtkU0kUo=
  - secure: XcLIqdhWI647Rjhw4YWGpsn/MsGQO6LrBYQ6vs1iyaOWpqHrzwmWRFjwensWEm25fl5vk7ud3t1x3PPIOmBtdgiSQzXdstG+BthftnzWAl9wR75o/hCk21eeF4inhI4VAeFv+UcZDwquB13lHIImrjLrlAKRsZ7vpntRPtT4cEk=
  - secure: Klk9sUI1FRL3E8ae2urgaHBixiwJBjPNL5vOPxOasmRBVgMn8LnKwEUpToiZI5iZGVfFFqCDgGnIddUWO4mnYddcSMP6OKglM4jSyDqMMMpR0j8LzZcNMAevXkedsIDxx9gNs+yUP+SBEQtobLbzkIl+VtQnJq4MSTpGPelMsZ4=
  - secure: Y+6qDS68rM/fM6Hc02Ro0/zKRWTkMkQVWMP5SnVtIYjNNLbCM6Gsh/HOq5wg5b9CjiGMG0FmNvdarZYMuApsEZ0Oc6aBQWSdGIaDLwPWNKe2svmKcp/LlvUF6PpsbsYHb8Ymp/xkdeITuinXlMh2eodt81Mw188IKnH0nh2vokc=
